// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Migrations need a DIRECT Postgres connection.
// Supabase pooler (port 6543 / pgbouncer) often makes `migrate` hang.
// Prefer DIRECT_URL (port 5432); fall back to DATABASE_URL for local DBs.
const migrateUrl =
  process.env["DIRECT_URL"] || process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --experimental-strip-types prisma/seed.js",
  },
  datasource: {
    url: migrateUrl,
  },
});
